README.md

We'd like to share this code for the .proto template file across all language workers to keep from getting out of sync and to keep from having to add changes to each repo manually.
(See here: https://github.com/Azure/azure-functions-host/issues/2296)
The current proposed solution is to share this repo using git. This PR describes the process. Alternatively, we could share this code using language-respective package managers. The git approach seemed like a simpler solution since we are just sharing the template file and not language-specific files.

Adding instructions for sharing this repo

---

src/proto/FunctionRpc.proto

Http headers can only be valid Ascii characters. Language workers and Functions Host need to handle converting other types of values to strings before sending message over grpc.
[Http RFC](https://tools.ietf.org/html/rfc2616#section-4.2)

Update headers in RpcHttp to <string, string>

---

src/proto/FunctionRpc.proto

Added new message to support reloading of environment variables. This message is specifically used during specialization when functions runtime starts a language worker in place holder mode and then assigns to an app at a later point in time.

Add support to reload environment variables

---

src/proto/FunctionRpc.proto

For issue https://github.com/Azure/azure-functions-host/issues/3921. Needed to implement https://github.com/Azure/azure-functions-python-worker/issues/66. 
Example queue trigger
```
def main(msg) -> None
```
above function defaults to converting msg to type QueueMessage defined in [azure-functions-python-library](https://github.com/Azure/azure-functions-python-library)
If user wants to receive msg as a String, dataType in function.json will be set to String

Adding dataType to BindingInfo

---

src/proto/FunctionRpc.proto
src/proto/deps/IdentityRpc.proto
src/proto/identity/ClaimsIdentityRpc.proto

Adds definitions for ClaimsPrincipal binding on RpcHttp. New message definitions are separated into their own subfolder which can be used for other additional definitions going forward.

Added identity folder and ClaimsIdentityRpc.proto.

---

src/proto/FunctionRpc.proto

Expose option to set `same-site=none` in an http cookie
Addresses https://github.com/Azure/azure-functions-host/issues/4890
Adds ability for out-of-proc workers to explicitly set "SameSite=None" (details [here](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html))
Because we already named our default "None" (which actually means "unspecified"), the new property is called "ExplicitNone"
Functions Host PR here: https://github.com/Azure/azure-functions-host/pull/5757
Node.js worker PR here: https://github.com/Azure/azure-functions-nodejs-worker/pull/286

Allow same-site=none property in cookie

---

src/proto/FunctionRpc.proto

`FunctionsMetadataRequest`
> Sends the function app directory to the worker.
`FunctionMetadataResponses`
> Includes a list of `FunctionLoadRequest` messages and an overall `StatusResult` attribute.

Add worker indexing message types to protobuf

---

src/proto/FunctionRpc.proto

Merging dev -> main v1.5.1 release

Merge dev into main

---

src/proto/FunctionRpc.proto

Related issue - https://github.com/Azure/azure-functions-host/issues/7916
Adding useDefaultMetadataIndexing field to FunctionMetadataResponses to allow worker to deny indexing if it could not index and then host will perform the indexing.

Added useDefaultMetadataIndexing field to FunctionMetadataResponses

---

src/proto/FunctionRpc.proto

Adding a change missed from [this Stein PR from yesterday](https://github.com/Azure/azure-functions-language-worker-protobuf/commit/18a91f6f72973ef3610cd985aa450f6fb4b7cf26). 
`FunctionMetadataResponses` was updated to `FunctionMetadataResponse` with no "s" and that change needed to be reflected  in the type `StreamingMessage`.

Edit streaming message types

---

src/proto/FunctionRpc.proto

Changes in host - https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto#:~:text=string%20config_source%20%3D%2012%3B-,//%20unique%20function%20identifier%20(avoid%20name%20collisions%2C%20facilitate%20reload%20case),bool%20managed_dependency_enabled%20%3D%2014%3B,-%7D

Added fields to sync with host on RPCFunctionMetadata

---

src/proto/FunctionRpc.proto

Issue - https://github.com/Azure/azure-functions-host/issues/7880
PR in Host - https://github.com/Azure/azure-functions-host/pull/8054
Host should have an ability to send a single FunctionLoadRequest in case of multiple functions in Function App.

Adding new field to send a list of load requests in case of multiple functions

---

src/proto/FunctionRpc.proto

Maintain consistency with field naming by using underscores rather than camel case

Change a field from camel case to underscores

---

src/proto/FunctionRpc.proto

Issue - https://github.com/Azure/azure-functions-host/issues/8082
Adding new field FunctionLoadResponseCollection to allow worker to send list of load responses to host. Worker can choose to send load responses one by one using FunctionLoadResponse or in batch using FunctionLoadResponseCollection.

Adding field to allow worker to send list of load responses to host

---

src/proto/FunctionRpc.proto

There's been a few issues on the node worker where we want to adjust our behavior based on the user's package.json file (i.e. https://github.com/Azure/azure-functions-nodejs-worker/issues/531 and https://github.com/Azure/azure-functions-nodejs-worker/issues/522). I'm not aware of any way to get the function app dir unless we're using the worker indexing feature (aka `FunctionsMetadataRequest`), but that's still in preview and the linked issues feel more related to "initialization" vs "worker indexing" anyways.

Add function app dir to worker init request

---

src/proto/FunctionRpc.proto

Added the following fields for the scenario in which user code throws an exception: 
- exception type name
- bool for isUserException, to be set by each worker upon throwing the exception.
These were added so that the user code exception can be piped through to AI and avoid customer confusion.

Added fields to RpcException message for surfacing in AppInsights

---

src/proto/FunctionRpc.proto

Undo removal of worker heartbeat message (#71)

Undo removal of worker heartbeat message

---

src/proto/FunctionRpc.proto

Updating the protobuf to capture additional worker information required for telemetry. 
Property format | Description | Examples
-- | -- | --
runtime_name | The runtime/stack name | Node, PowerShell, Java, .NET, .NET Framework, Python, etc.
runtime_version | The version of the runtime/stack  |  Such as the version of .NET or Python etc.
worker_version | The version of the worker |  
worker_bitness | The worker bitness/architecture | x86, x64, arm64
custom_properties | Additional worker specific custom properties | Usage of custom containers vs first-party image containers, npm package, the version of the SDK used in .NET Isolated, etc.

Add WorkerMetadata message to WorkerInitResponse

---

src/proto/FunctionRpc.proto

Related issue: https://github.com/Azure/azure-functions-dotnet-worker/issues/1035
A protobuf message for sending [ParameterBindingData](https://github.com/Azure/azure-webjobs-sdk/blob/7fbc0e6a9e629c01a728c0f7e38cae5130f7139a/src/Microsoft.Azure.WebJobs/ParameterBindingData.cs) from the host to the workers; this is used to hydrate SDK-type bindings.
- [Internal design doc for reference](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/Design/OOPWorkers/SDKTypeBindings.md&version=GBmaster&_a=preview)
- [Usage of message in the host](https://github.com/Azure/azure-functions-host/blob/2d1af23fff17c2f7c2270d201a3abbeb8612372b/src/WebJobs.Script.Grpc/MessageExtensions/GrpcMessageConversionExtensions.cs#L68-L84)
- [Usage of message in the …

Add new message to support model-type bindings for OOP workers

---

src/proto/FunctionRpc.proto

Updated case of RpcMetadata Properties to lower case

Updated case of RpcMetadata Properties

---

src/proto/FunctionRpc.proto

Issue - https://github.com/Azure/azure-functions-dotnet-worker/issues/1156
Epic - https://github.com/Azure/azure-functions-dotnet-worker/issues/1081
A protobuf message for sending the collection of [ParameterBindingData](https://github.com/Azure/azure-webjobs-sdk/blob/7fbc0e6a9e629c01a728c0f7e38cae5130f7139a/src/Microsoft.Azure.WebJobs/ParameterBindingData.cs) from the host to the workers; this is used to hydrate SDK-type bindings.
Message for ModelBindingData - [Link](https://github.com/Azure/azure-functions-language-worker-protobuf/pull/83)
Usage in Host - [Link](https://github.com/Azure/azure-functions-host/blob/ba628f81c672a5ebdbafb9c0c8a65d3b174b68ee/src/WebJobs.Script.Grpc/MessageExtensions/GrpcMessageConversionExtensions.cs#L59)
Usage in Worker - …

Add new message to support collection of model-type bindings for OOP workers

---

src/proto/FunctionRpc.proto

Add capabilities and worker metadata in env reload response. This is to support changes needed for https://github.com/Azure/azure-functions-host/issues/8983
Currently worker metadata and capabilities are sent in the worker init response. But this is not valid for placeholder & specialization use case. When in placeholder mode, this information is not available. It is available only after specialization (env reload request). So we need to include this information in the env reload response.
I added 1 and 2 as the order for these new props as the existing `result` property(the only property existed in this type) was using 3. I looked at this history of this and found that PR #20  added this type and status property. This type never had a property with order value 1 and 2. So I am guessing …

Add capabilities and worker_metadata in env reload response.

---

src/proto/FunctionRpc.proto

New protobuf message for warming up worker code path before specialization. 
- [Design doc](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs/pullrequest/7030389?_a=files)
- [Draft host changes](https://github.com/Azure/azure-functions-host/pull/9018/files)
- [Draft Java worker changes](https://github.com/Azure/azure-functions-java-worker/pull/672/files)

Worker code path warmup
